### ISSUE TITLE
Add support for DocOnce

### ISSUE THREAD

**Issue by dumblob** [n457/Uncolored#22]
Markdown (including it's flavours) nor CommonMark support the features requested in https://github.com/n457/Uncolored/issues/2 , https://github.com/n457/Uncolored/issues/19 , https://github.com/n457/Uncolored/issues/20 , and many others (e.g. image positioning, underlined text, verbatim blocks, wiki features, quizes, page breaks, slides, etc.).

To cleanly solve this issue, I would recommend supporting the [DocOnce](https://github.com/hplgit/doconce ) markup language instead/in_addition_to CommonMark/Markdown. DocOnce is the only existing markup language capable of producing sizeable output (HTML, etc.) as well as fixed-size outputs like PDF (research papers, etc.), books, LaTeX, quizes, slides, and potentially other outputs. DocOnce has already been used for producing **all** the mentioned outputs already for several years and is thus well-proven. And of course, DocOnce is as easy to write as CommonMark/Markdown.

**Comment by n457** [comment]
Hello @dumblob,

My main concern about DocOnce is that it's **a Python package** that has, moreover, a lot of dependencies

![image](https://cloud.githubusercontent.com/assets/11824581/20273055/309770fe-aa90-11e6-9ca9-52cedfc380a4.png)

I want (Un)colored to stay a **lightweight** & performant application (most of the weight of the app is due to Electron framework).
I don't want **the average user** to have to download and install Python, DocOnce package and its dependencies, or **to worry about any optionnal thing** like "What's this DocOnce thing, why I do not have it ?".

Concerning the DocOnce features you listed :
- **image positioning** : available via themes
- **underlined text** : available
- **verbatim blocks** : available soon
- **wiki features, quizes, page breaks, slides** : not the point of the app

**The ideal compromise** would be to have a **JS library / Node.js module** that converts HTML / Markdown to DocOnce language.

I let this topic open, I'm still open to discussion and propositions.

Thanks for your feedback

**Comment by dumblob** [comment]
@n457 thanks for the feedback.

> most of the weight of the app is due to Electron framework

I know and must agree it's a shame. But it's an already made choice.

> to download and install Python, DocOnce package and its dependencies

I totally agree. It's though a technically solvable issue (e.g. through ugly bundling the Python packages using [PEX](https://github.com/pantsbuild/pex)). But see bellow.

> image positioning : available via themes

This and many similar positioning/sizing related issues were immensely discussed in CommonMark forum https://talk.commonmark.org/ and the result was, that it's an utterly needed feature directly in the markup language and **not** as theme/style, but because of compatibility issues it won't be incorporated into CommonMark.

> underlined text : available

Not supported by CommonMark nor the original Markdown. So this feature makes the syntax a specific Uncolored Mardown flavor.

> wiki features, quizes, page breaks, slides : not the point of the app

I did not know that. This totally changes the situation. Based on this it doesn't make any sense to change anything (as this predestines Uncolored staying _yet another non-standard/flavored Markdown GUI editor_).

> The ideal compromise would be to have a JS library / Node.js module that converts HTML / Markdown to DocOnce language.

Actually the idea was quite the opposite :smile: - namely to support the biggest needed superset of features (which only DocOnce satisfies) and then possibly convert to other formats.

Anyway, thank you for clarification of the goals of this project and keep going! I'm closing this issue as invalid.

**Comment by n457** [comment]
Alright,

Don't hesitate to submit ideas, bugs, etc. It's not because this idea wasn't accepted this time that this will be the case next time :)
